import { notFound, redirect } from "next/navigation";
import type { Metadata } from "next";
import { DocsBody, DocsDescription, DocsPage, DocsTitle } from "fumadocs-ui/layouts/docs/page";
import { createRelativeLink } from "fumadocs-ui/mdx";
import { source } from "@/lib/source";
import { getMDXComponents } from "@/mdx-components";
import { openapi } from "@/lib/openapi";
import { OpenAPIPage } from "@/components/api-page";
import type { GeneratedPageProps } from "fumadocs-openapi";

interface PageParams {
  params: Promise<{ slug?: string[] }>;
}

export default async function Page({ params }: PageParams) {
  const { slug } = await params;

  if (!slug || slug.length === 0) {
    redirect("/docs/guide");
  }

  const page = source.getPage(slug);
  if (!page) notFound();

  const MDX = page.data.body;

  // Pages generated by fumadocs-openapi (see scripts/generate-openapi.mjs) carry an
  // `_openapi.preload` frontmatter list naming which schema(s) their <OpenAPIPage/>
  // needs — resolve that server-side and hand it down as the `preloaded` prop.
  const openapiMeta = (page.data as { _openapi?: { preload?: string[] } })._openapi;
  const preloaded = openapiMeta?.preload ? (await openapi.preloadOpenAPIPage(page)).preloaded : undefined;

  return (
    <DocsPage toc={page.data.toc} full={page.data.full}>
      <DocsTitle>{page.data.title}</DocsTitle>
      <DocsDescription>{page.data.description}</DocsDescription>
      <DocsBody>
        <MDX
          components={getMDXComponents({
            a: createRelativeLink(source, page),
            ...(preloaded && {
              OpenAPIPage: (props: GeneratedPageProps) => <OpenAPIPage preloaded={preloaded} {...props} />,
            }),
          })}
        />
      </DocsBody>
    </DocsPage>
  );
}

export function generateStaticParams() {
  return source.generateParams();
}

export async function generateMetadata({ params }: PageParams): Promise<Metadata> {
  const { slug } = await params;
  if (!slug || slug.length === 0) return {};

  const page = source.getPage(slug);
  if (!page) notFound();

  return {
    title: page.data.title,
    description: page.data.description,
  };
}
