import { defineRouting } from "next-intl/routing";
import { DEFAULT_LOCALE, LOCALE_CODES } from "./locales";

// "as-needed" (no prefix for the default locale, e.g. "/dashboard" not "/en/dashboard") only
// works because src/proxy.ts's middleware rewrites the unprefixed URL to the default locale on
// every request. The demo build is a static export with no server to run that middleware (see
// the app/page.tsx root-redirect fix for the same underlying issue), so every unprefixed English
// link/redirect generated by @/i18n/navigation's Link/redirect would point at a URL with no
// matching static file. Forcing "always" there means every generated href is explicitly
// prefixed (e.g. "/en/dashboard"), matching what generateStaticParams actually emits.
const isDemoMode = process.env.NEXT_PUBLIC_DEMO_MODE === "true";

export const routing = defineRouting({
  locales: LOCALE_CODES,
  defaultLocale: DEFAULT_LOCALE,
  localePrefix: isDemoMode ? "always" : "as-needed",
});
